show_grid: false

# Player options
playable: true
player_step_time: 2
full_screen: true

no_steps: 10
no_lanes: 1
random_walkers: 0
random_features:
  Blocker: 0
  Exit: 0
  Entrance: 0
  Portal: 0

levels:
  - map: 'easy_campaign/01-simple'
    target: 5
  - map: 'easy_campaign/02-blocking'
    target: 5
  - map: 'easy_campaign/03-in_out'
    target: 5
  - map: 'easy_campaign/04-portal'
    target: 5
