show_grid: false

# Player options
playable: true
player_step_time: 2

no_steps: 20
no_lanes: 3
target: 15

# Random placement
random_walkers: 1
random_features:
  Blocker: 5
  Exit: 1
  Entrance: 1
  Portal: 1
  Coin: 1
